### ISSUE TITLE
Cannot find module '../test/chain'.

### ISSUE THREAD

**Issue by aakldey** [valor-software/ngx-bootstrap#3554]
When I run build locally it works fine, but when I run it with gitlab pipeline (in docker container, node 9.2.0, yarn 1.4.0) to deploy my application with gradle and node plugin, it fails:

`ERROR in node_modules/ngx-bootstrap/chronos/create/parsing.types.d.ts(3,27): error TS2307: Cannot find module '../test/chain'.
node_modules/ngx-bootstrap/chronos/create/local.d.ts(1,27): error TS2307: Cannot find module '../test/chain'.
`
There is nothing special in run script, it's just `ng build --prod`
And it was working 1-2 days before with ngx-bootstrap 2 beta

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 2.0.2

Angular: 5

Bootstrap: 3

**Comment by aakldey** [comment]
problem was in .yarnclean file. I've removed test folders from there and it works

**Comment by AterDeus** [comment]
I got same issue, but don't use yarn, so no .yarnclean file.
It happend after i updated from 4.3.0 to 5.0.0. Angular version is 7
