### ISSUE TITLE
Integration with ng2 seeds

### ISSUE THREAD

**Issue by ravi-mone** [valor-software/ngx-bootstrap#18]
@jimthedev @valorkin 
I could able to solve the integration of ng-bootstrap2 alert box in angular-seed app,
https://github.com/AngularShowcase/github-api-sample-app
 works with `.js` files, so needed to convert all `.ts` files to `.js` .
And in the process:

I was getting some issue like:
`EXCEPTION: Cannot resolve all parameters for Alert(?). Make sure they all have valid type or annotations.`

 So I was forced to add some code in your component alert.ts file
- import {... Inject, Injectable,... } from 'angular2/angular2';
- @Injectable()
-  constructor(@Inject(ElementRef) public el:ElementRef) {
  this.closeable = this.closeable || el.nativeElement.getAttribute('(close)');
  }

And then the things starts working, 
- But ideally this should have not happened, 
- Please let me know if you have any alternative solution

---

Likewise there are remaining components, which is not allowing to merge with angular-seed or with ES5 
NOTE: I am not sure, it is the problem of ng2-bootstrap or the angular2-seed application configuration, just brt to your notice

**Comment by valorkin** [comment]
@ravi-mone ElementRef working without Inject with ts 1.5 and 1.6, if it is not then something wrong with generated es5 meta
if you are installing via npm, it already works with js version of files, why you have to convert it once more?
I will check seed repo when will have a bit of time

**Comment by be4code** [comment]
I'm using https://github.com/mgechev/angular2-seed and I also have problem with injecting files but for me:
./node_modules/ng2-bootstrap/dist/module.d.ts(2,19): error TS2307: Cannot find module 'index'

**Comment by valorkin** [comment]
TS produces a lot more errors, let us wait this friday
should be release of 0.40 with .d.ts for DI\core etc

**Comment by ghost** [comment]
@valorkin ,
Friday has come, :), So it is fixed?

**Comment by valorkin** [comment]
@ravi-tj 0.40 released only 7 hours ago https://github.com/angular/angular/releases/tag/2.0.0-alpha.40
I will update this tread when I check it is working fine with ng2-seed

**Comment by valorkin** [comment]
updated to v0.40, working on consistent typing's for ng2-bootstrap

**Comment by valorkin** [comment]
bootstrap updated to use ng2 0.44 and sample app updated too
you can check it here
https://github.com/valor-software/angular2-bootstrap-starter

**Comment by be4code** [comment]
After running npm install ng2-bootstrap --save  I've got: error TS2300: Duplicate identifier 'Zone'.   

And many many more similiar errors

**Comment by valorkin** [comment]
1. check this one https://github.com/ocombe/ng2-translate/pull/1#issuecomment-147971653
   most probably you have tsd typings - remove them
2. check https://github.com/valor-software/angular2-bootstrap-starter
   it doesn't have such problems

**Comment by be4code** [comment]
1. ok, I'll check this.
2. Starter doesn't have that problem because it uses webpack and typescript
   instead of JS, what is more I'm using express and gulp inject
   17 paź 2015 23:26 "Dmitriy Shekhovtsov" notifications@github.com
   napisał(a):

**Comment by valorkin** [comment]
what you was using? as started repo?

**Comment by be4code** [comment]
https://github.com/mgechev/angular2-seed
17 paź 2015 23:39 "Dmitriy Shekhovtsov" notifications@github.com
napisał(a):

**Comment by valorkin** [comment]
it uses ng2 alfa41, sec

**Comment by be4code** [comment]
after updating to 44 there was still wrong. For me the most important thing
is that I cannot simply add your's lib in workflow.config.js as other libs.
:(
17 paź 2015 23:42 "Dmitriy Shekhovtsov" notifications@github.com
napisał(a):

**Comment by valorkin** [comment]
how did you updated to ng2 44?
PR with it still broken https://github.com/mgechev/angular2-seed/pull/163
use webpack or systemsjs it will be much easier for you
other angular2 libs?

**Comment by valorkin** [comment]
Just to keep you updated:
- I have update ng2-bootstrap to be builded with noImplicitAny:any
- thanks to @ocombe , figured out problems with ng2-seeds: https://github.com/pkozlowski-opensource/ng2-play/pull/32
- and problem with type duplications

stay tuned :)

**Comment by valorkin** [comment]
@be4code ok, here we go https://github.com/pkozlowski-opensource/ng2-play/pull/34
now you can use ng2-bootstrap with your favourite ng2-seed :)

**Comment by be4code** [comment]
It seems that I still can't use it but I don't have skill enough to do it... Your starter works perfectly but I can't add RX lib which one I need. In my project RX works but your library doesn't...

**Comment by valorkin** [comment]
Check versions, most probably it is nothing to do with my lib
