### ISSUE TITLE
Datepicker No value accessor for '' error still there after updating to 1.0.20 ...

### ISSUE THREAD

**Issue by rernens** [valor-software/ngx-bootstrap#722]
After upgrading to Angular 2.0.0 RC 4 and ng2-bootstrap 1.0.20, despite issue #678 being merged in version, issue #680 is still there.

I can't get the sample from your web site  to work and always get the « No value accessor for '' » exception

platform-browser.umd.js:1900 Error: No value accessor for ''
    at new BaseException (exceptions.ts:21)
    at _throwError (shared.ts:68)
    at Object.setUpControl (shared.ts:39)
    at NgModel._setUpStandalone (ng_model.ts:83)
    at NgModel._setUpControl (ng_model.ts:73)
    at NgModel.ngOnChanges (ng_model.ts:43)
    at DebugAppView._View_TeetimesComponent0.detectChangesInternal (TeetimesComponent.template.js:260)
    at DebugAppView.AppView.detectChanges (core.umd.js:12143)
    at DebugAppView.detectChanges (core.umd.js:12247)
    at DebugAppView.AppView.detectViewChildrenChanges (core.umd.js:12169)

**Comment by Dinistro** [comment]
@rernens Did you provide the new forms and disabled the deprecated once?

**Comment by valorkin** [comment]
@rernens please add this 2 lines to application bootstrap
https://github.com/valor-software/ng2-bootstrap/blob/development/demo/index.ts#L57-L58
and use ngModel\FORM_DIRECTIVES from `@angular/forms`

**Comment by rernens** [comment]
I am effectively using the new form and have properly disabled the old one as per the @valorkin comments.

**Comment by valorkin** [comment]
@rernens so it works now?

**Comment by rernens** [comment]
@valorkin I was already using the new form since RC 3. Had already applied your 2 lines before reporting the problem.
No the problem is still there.
I have a similar problem with ngFormControl also getting the same exception.
What does that mean ?

**Comment by valorkin** [comment]
Can you create a plunkr?

**Comment by adamduren** [comment]
I am experiencing this problem as well but for the Typeahead component. Should I open another issue?

**Comment by valorkin** [comment]
Not really, please check steps I was mentioning earlier

**Comment by adamduren** [comment]
I followed those steps and the outcome was the same. I did a little more digging to try to figure out what exactly it was and it appears that it has to do with Ionic and the `<ion-input>` directive. When I converted it to a regular input it worked fine. Any ideas?

**Comment by adamduren** [comment]
Ok in my case it appears to be this bug https://github.com/driftyco/ionic/issues/7217. I removed the typeahead directives with the exception of ngModel and the issue remained. Any chance you are using Ionic 2 as well @rernens?

**Comment by Dinistro** [comment]
@valorkin @adamduren @rernens I fixed this for the typeaheads. If I have enough time, I will apply these changes to every directive that uses ngModel. 
See #723

**Comment by Dinistro** [comment]
See #723

**Comment by rernens** [comment]
@adamduren No I am not using Ionic 2. I am using the advanced-seed with nativescript support but the problem appears in the web part. Not yet tested on nativescript.

**Comment by rernens** [comment]
@valorkin Do you still nee a plunkr, if yes I will create one.

**Comment by Dinistro** [comment]
@rernens We don't need a plunkr, I now exactly what the problem is.

**Comment by rernens** [comment]
@dinistro OK, looking forward for your solution. Thanks

**Comment by rernens** [comment]
@Dinistro I finally found where the issue was, not a bug in datepicker :

import {disableDeprecatedForms, provideForms} from '@angular/forms';

not

import {disableDeprecatedForms, provideForms} from '@angular/forms/index';

**Comment by Dinistro** [comment]
@rernens there is another issue, if you use the directives without ngModel.

**Comment by davidgfolch** [comment]
ng2-bootstrap need to be updated to 1.0.22 for @angular/forms compatibility

**Comment by rernens** [comment]
@Dinistro OK thanks for the info. 
In my case I am using the directive with ngModel so I have not noticed this issue.

**Comment by msklvsk** [comment]
Happens for me with radio button. Latest everything, importing from `@angular/forms`, bootstrapping `disableDeprecatedForms()` and `provideForms()`. Is it more likely that I'm missing something or the issue still exists?

**Comment by valorkin** [comment]
@msklvsk > ng2-bootstrap need to be updated to 1.0.22 for @angular/forms compatibility
