### ISSUE TITLE
Cannot build with ngx-bootstrap@1.9.2 

### ISSUE THREAD

**Issue by gastonambrogi** [valor-software/ngx-bootstrap#2597]
Building Angular 2 project with `ng build -prod` gets this error 

`ERROR in .../node_modules/ngx-bootstrap/datepicker/bs-datepicker.component.d.ts (46,15): Cannot find name 'Partial'.`

`ERROR in .../node_modules/ngx-bootstrap/datepicker/bs-daterangepicker.component.d.ts (45,15): Cannot find name 'Partial'.`

**Comment by IlyaSurmay** [comment]
Which version of TypeScript are you using? `Partial` was introduced in Typescript 2.1

**Comment by valorkin** [comment]
typescript 2.4+ and latest rxjs is required

**Comment by eva-Z** [comment]
Have you solved the problem?

**Comment by gastonambrogi** [comment]
I attached this package to 1.9.1 because I'm using TS 2.0.10

**Comment by valorkin** [comment]
Upgrade to ts 2.4.2 is mandatory, cuz it's mandatory for angular v5+

**Comment by ekaitzht** [comment]
For me not working 1.9.1 @gastonambrogi can you attach your package.json? Thanks

**Comment by jpoornimaprasanna** [comment]
How to solve this problem? I updated ts to 2.9.1   still it's showing the same error
