### ISSUE TITLE
Getting error in Latest version of Angular 2

### ISSUE THREAD

**Issue by pradeepverse** [valor-software/ngx-bootstrap#1245]
I've set up the ng2-bootstrap, by following the steps mentioned in your page.
I'm getting the following error in console when I try to click the button which opens modal...
`self._el_112.show is not a function`
Kindly help me with this issue.

**Comment by valorkin** [comment]
can you provide plunkr with reproduce please

**Comment by veliancreate-zz** [comment]
Im getting the following:

![screenshot from 2016-11-18 10-28-28](https://cloud.githubusercontent.com/assets/7488209/20427042/d95990fa-ad79-11e6-95d4-d5d75e2403f3.png)

**Comment by SergeyKuryatnick** [comment]
@veliancreate 
You can look for some ideas from this issue:
https://github.com/valor-software/ng2-bootstrap/issues/986#issue-177218652

**Comment by Confusedfish** [comment]
I hit this problem too, not had time to create a PR for this yet but the following change seems to work for me:

components-helper-service.**js**
`55.            this.root = rootComponent.instance.viewContainerRef;`

Note: this still requires the viewContainerRef hack on the root App. rootComponent.instance is just instead of accessing via the internal _hostElement property which seems to have been removed in angular@2.2.0

Hope the above helps and I will attempt to find time to create a PR

**Comment by xtreemrage** [comment]
I have the same issue as @veliancreate with Angular 2.2.x and ng2-bootstrap models, it worked fine with Angular 2.1.x.

I get the following:
```javascript
error_handler.js:53 Error: ApplicationRef instance not found
    at ComponentsHelper.getRootViewContainerRef (components-helper.service.js:59)
    at ComponentsHelper.appendNextToRoot (components-helper.service.js:94)
    at ModalDirective.showBackdrop (modal.component.js:191)
    at ModalDirective.show (modal.component.js:108)
    at ScenarioComponent.showJobsModal (scenario.component.ts:71)
    at CompiledTemplate.proxyViewClass.View_ScenarioComponent0.handleEvent_117 (component.ngfactory.js:910)
    at CompiledTemplate.proxyViewClass.<anonymous> (view.js:408)
    at HTMLElement.<anonymous> (dom_renderer.js:276)
    at ZoneDelegate.invokeTask (zone.js:265)
    at Object.onInvokeTask (ng_zone.js:227)
```

When I use @Confusedfish solution, it idd works with Angular 2.2.x!

This works 2: https://github.com/valor-software/ng2-bootstrap/issues/986#issuecomment-262293199 and is for the moment the better solution until ng2-bootstrap team brings a fix

ng2-bootstrap version `"ng2-bootstrap": "^1.1.14",`

**Comment by valorkin** [comment]
Hack producing this issue, removed

**Comment by Avien** [comment]
I also have this problem

**Comment by valorkin** [comment]
Versions?
