### ISSUE TITLE
Typings error after updating ng2-b and angular

### ISSUE THREAD

**Issue by Nalha** [valor-software/ngx-bootstrap#982]
`
[default] project/node_modules/ng2-bootstrap/components/buttons/button-checkbox.directive.d.ts:14:13 
    Duplicate identifier 'readonly'.
[default] project/node_modules/ng2-bootstrap/components/buttons/button-checkbox.directive.d.ts:14:22 
    '=' expected.
[default] project/node_modules/ng2-bootstrap/components/buttons/button-checkbox.directive.d.ts:14:22 
    Cannot find name 'trueValue'.
[default] project/node_modules/ng2-bootstrap/components/buttons/button-checkbox.directive.d.ts:15:13 
    Duplicate identifier 'readonly'.
[default] project/node_modules/ng2-bootstrap/components/buttons/button-checkbox.directive.d.ts:15:22 
    '=' expected.
[default] project/node_modules/ng2-bootstrap/components/buttons/button-checkbox.directive.d.ts:15:22 
    Cannot find name 'falseValue'.
[default] project/node_modules/ng2-bootstrap/components/buttons/button-radio.directive.d.ts:10:14 
    '=' expected.
[default] project/node_modules/ng2-bootstrap/components/buttons/button-radio.directive.d.ts:10:14 
    Cannot find name 'isActive'.
[default] project/node_modules/ng2-bootstrap/components/buttons/button-radio.directive.d.ts:10:22 
    ';' expected.
[default] project/node_modules/ng2-bootstrap/components/dropdown/dropdown-toggle.directive.d.ts:11:14 
    '=' expected.
[default] project/node_modules/ng2-bootstrap/components/dropdown/dropdown-toggle.directive.d.ts:11:14 
    Cannot find name 'isOpen'.
[default] project/node_modules/ng2-bootstrap/components/dropdown/dropdown-toggle.directive.d.ts:11:20 
    ';' expected.
[default] project/node_modules/ng2-bootstrap/components/modal/modal.component.d.ts:15:5 
    Duplicate identifier 'readonly'.
[default] project/node_modules/ng2-bootstrap/components/modal/modal.component.d.ts:15:14 
    '=' expected.
[default] project/node_modules/ng2-bootstrap/components/modal/modal.component.d.ts:15:14 
    Cannot find name 'isShown'.
[default] project/node_modules/ng2-bootstrap/components/modal/modal.component.d.ts:15:21 
    ';' expected.
[default] project/node_modules/ng2-bootstrap/components/modal/modal.component.d.ts:23:13 
    Duplicate identifier 'readonly'.
[default] project/node_modules/ng2-bootstrap/components/modal/modal.component.d.ts:23:22 
    '=' expected.
[default] project/node_modules/ng2-bootstrap/components/position.d.ts:29:13 
    Duplicate identifier 'readonly'.
[default] project/node_modules/ng2-bootstrap/components/position.d.ts:29:22 
    '=' expected.
[default] project/node_modules/ng2-bootstrap/components/position.d.ts:30:13 
    Duplicate identifier 'readonly'.
[default] project/node_modules/ng2-bootstrap/components/position.d.ts:30:22 
    '=' expected.
[default] project/node_modules/ng2-bootstrap/components/tooltip/tooltip-container.component.d.ts:21:14 
    '=' expected.
[default] project/node_modules/ng2-bootstrap/components/tooltip/tooltip-container.component.d.ts:21:14 
    Cannot find name 'isTemplate'.
[default] project/node_modules/ng2-bootstrap/components/tooltip/tooltip-container.component.d.ts:21:24 
    ';' expected.
[default] project/node_modules/ng2-bootstrap/components/typeahead/typeahead-container.component.d.ts:18:14 
    '=' expected.
[default] project/node_modules/ng2-bootstrap/components/typeahead/typeahead-container.component.d.ts:18:14 
    Cannot find name 'itemTemplate'.
[default] project/node_modules/ng2-bootstrap/components/typeahead/typeahead-container.component.d.ts:18:26 
    ';' expected.
[default] project/node_modules/ng2-bootstrap/components/typeahead/typeahead-container.component.d.ts:18:40 
    Type parameter name cannot be 'any'
[default] project/node_modules/ng2-bootstrap/components/typeahead/typeahead-container.component.d.ts:18:44 
    '(' expected.
[default] project/node_modules/ng2-bootstrap/components/typeahead/typeahead.directive.d.ts:46:14 
    '=' expected.
[default] project/node_modules/ng2-bootstrap/components/typeahead/typeahead.directive.d.ts:46:14 
    Cannot find name 'matches'.
[default] project/node_modules/ng2-bootstrap/components/typeahead/typeahead.directive.d.ts:46:21 
    ';' expected.
[default] project/node_modules/ng2-bootstrap/components/typeahead/typeahead.directive.d.ts:46:29 
    Type parameter name cannot be 'any'
[default] project/node_modules/ng2-bootstrap/components/typeahead/typeahead.directive.d.ts:46:33 
    '(' expected.
`

This appeared after updating to angular 2.0.0 and ng2-bootstrap to 1.1.4, is this supposed to work?

**Comment by acostaf** [comment]
+1

**Comment by kubosador** [comment]
Same here with webpack and RC6 and ng2-bootstrap 1.1.4

```


(29,22): error TS1005: '=' expected.                                                                                                                                                      
(30,22): error TS1005: '=' expected. 
```

**Comment by MathAndrews** [comment]
I have the same problem.
Running 2.0.0-rc.6 with webpack
install ng2-bootstrap 1.1.4

**Comment by ghost** [comment]
I have the same issue after upgrading to Angular 2.0.0 and ng2-bootstrap 1.1.4.

**Comment by tungphuong** [comment]
I have the same issue when upgrade to ver 1.1.4 and angular 2.0 with systemjs

**Comment by valorkin** [comment]
most probably you are using typescript 1.8?

**Comment by ghost** [comment]
Yes, TypeScript 1.8.10

**Comment by valorkin** [comment]
.d.ts files have changed between ts 1.8 & 2.0.2
for example

``` ts
    private trueValue;
    private falseValue;
// changed too
    private readonly trueValue;
    private readonly falseValue;
```

**Comment by valorkin** [comment]
Yeap, I have to update ng2-bootstrap to typescript 2 because angular2 is using ts 2 too already

**Comment by requiemforameme** [comment]
Confirmed.  Upgrading version of typescript package to "^2.0.0" in package.json does the trick.

**Comment by tungphuong** [comment]
Hello, I upgrade typescript to 2.0.2 but still meet error

components/buttons/button-checkbox.directive.d.ts(14,22): error TS1005: '=' expected.

**Comment by adrianfaciu** [comment]
@jackyphuong how do you transpile the files ? Some tools (like gulp-typescript) might use an older bundled version of typescript and you'll end up still having the error.

**Comment by tungphuong** [comment]
I am using gulp-typescript": "^2.13.6", so is it ok?

**Comment by adrianfaciu** [comment]
@jackyphuong It uses an older version of typescript. You have to explicitly tell it to use something else.
When you create the project, in the task:

```
 var project = ts.createProject('tsconfig.json',  {
    typescript: require('typescript')
});
```

That will make it use whatever version you have installed.

**Comment by tungphuong** [comment]
Thanks, it worked with me

**Comment by ctrl-brk** [comment]
How do I configure which typescript version to use in WebStorm and Visual Studio?
Have 2.0.2 in devdependencies. Should it be also installed global?

**Comment by adrianfaciu** [comment]
For WebStorm you should be able to change it from Settings => Language & Frameworks => Typescript and you should have a check to use a custom version, where you need to specify the install folder (so yes, might be a good idea to install it globally).

For Visual Studio you need to install the beta version of the plugin. Have a look in the [post announcing Typescript 2.0](https://blogs.msdn.microsoft.com/typescript/2016/07/11/announcing-typescript-2-0-beta/) (or install it globally with npm, it might pick it up right away).

**Comment by valorkin** [comment]
@adrianfaciu thanks for helping guys in solving issues! :)

**Comment by ctrl-brk** [comment]
Thanks, @adrianfaciu 

In my case for WebStorm I had to use this path:
C:\Users\[my_user_name]\AppData\Roaming\npm\node_modules\typescript\lib

For Visual Studio you have to run [the installer](http://download.microsoft.com/download/6/D/8/6D8381B0-03C1-4BD2-AE65-30FF0A4C62DA/TS2.0.0-TS-release20-nightly-20160708.1/TypeScript_Dev14Full.exe), just running `npm install -g typescript@beta` doesn't work even they say it does.

**Comment by Avien** [comment]
I'm getting these errors as well and using typescript 1.8.10
I don't want to use typescript 2
Is there a way to solve this?
Thanks

**Comment by adrianfaciu** [comment]
@Avien What's wrong with TypeScript 2 ? Angular project itself already uses it...
The only option is to use an older version of ng2-bootstrap, from before it was upgraded to TypeScript 2.

**Comment by Avien** [comment]
Nothing's wrong - I'm in a middle of a sprint with rough deadlines,
already have a project setup working with ts 1.8,
Cant deal with typescript regressions now

**Comment by Martin-Luft** [comment]
@Avien TypeScript 2 is backward compatible.

**Comment by Avien** [comment]
No need to change typings configuration and reinstall it?

**Comment by Martin-Luft** [comment]
Typings will work with TypeScript 2 and you can upgrade to @types later.

**Comment by Avien** [comment]
Then I will try it, thanks!
